
/* Formatted on 31/10/2018 17:37:53 (QP5 v5.256.13226.35538) */
SELECT V_POLICY_NO,
       N_SEQ_NO,
       V_REF_TYPE,
       N_PRINCIPAL,
       N_ACTUAL_INTEREST,
       N_WAIVE_INTEREST,
       N_WAIVE_SEQ,
       V_LASTUPD_USER,
       V_WAIVE_STATUS,
       V_LASTUPD_INFTIM
  FROM PSMT_POLICY_WAIVE_INTEREST
-- WHERE V_POLICY_NO IN NVL ( :V_POL_NO, V_POLICY_NO)
WHERE EXTRACT(YEAR FROM V_LASTUPD_INFTIM)<=2021