/* Formatted on 26/01/2019 21:23:04 (QP5 v5.256.13226.35538) */
SELECT COUNT (DISTINCT V_VOU_NO) FROM
(
SELECT A.V_POLICY_NO,
       V_NAME,
       D_CNTR_START_DATE,
       D_CNTR_END_DATE,
       N_CONTRIBUTION,
       N_TERM,
       V_PLAN_CODE,
       D.N_SEQ_NO,
       D_IND_DOB,
       N_IND_SA,
       N_WITH_REQ_NO,
       N_NET_DEPOSIT_PAID,
       N_DEPOSIT_PAID DEPOSIT_PAID,
       B.V_MAIN_VOU_NO,
       C.V_VOU_NO,
       V_VOU_SOURCE,
       V_VOU_DESC,
       D_VOU_DATE,
       DECODE (F.V_CURRENT_STATUS,
               'PY004', 'VOUCHER AWAITING PRINTING OR PRINT',
               'VOUCHER PENDING APPROVAL')
          VOUCHER_STATUS,
       N_VOU_AMOUNT,
       V_CHQ_NO,
       V_PAYEE_NAME
  FROM PSDT_DEPOSIT_PAYOUT A,
       PYMT_VOUCHER_ROOT B,
       PYMT_VOU_MASTER C,
       GNMT_POLICY_DETAIL D,
       PYDT_VOUCHER_PAYMENTS E,
       PY_VOUCHER_STATUS_LOG F
 WHERE     TO_CHAR (A.N_WITH_REQ_NO) = B.V_SOURCE_REF_NO(+)
       AND B.V_MAIN_VOU_NO = C.V_MAIN_VOU_NO(+)
       AND C.V_VOU_NO = E.V_VOU_NO
       AND C.V_VOU_NO = F.V_VOU_NO
       AND F.V_CURRENT_STATUS = 'PY004'
       AND N_NET_DEPOSIT_PAID > 0
       AND A.V_POLICY_NO = D.V_POLICY_NO
       AND A.N_SEQ_NO = D.N_SEQ_NO
       AND V_VOU_SOURCE = 'PR0045'
       AND E.V_INST_STATUS = 'A'
--       AND TRUNC (D_VOU_DATE) BETWEEN NVL ( :P_FM_DT, TRUNC (D_VOU_DATE))
--                                  AND NVL ( :P_TO_DT, TRUNC (D_VOU_DATE))
      --AND EXTRACT(YEAR FROM D_VOU_DATE) = 2023
      AND TO_CHAR(D_VOU_DATE, 'MON-YY') = 'JAN-24'
      )