/* Updated 11/05/2022 by Teddy Maina*/

select count(distinct V_CLAIM_NO) from 
(
SELECT A.V_CLAIM_NO,
       D.V_POLICY_NO,
       V_NAME,
       D_CNTR_START_DATE,
       D_PREM_PAYING_END_DATE,
       N_CONTRIBUTION,
       N_TERM,
       M.V_PLAN_CODE,
       M.V_PLAN_DESC,
       N_IND_SA,
       V_DESCRIPTION CLAIM_TYPE,
       V_STATUS_DESC CLAIM_STATUS,
       NVL (N_AMOUNT_PAYABLE, 0) CLAIM_PROV,
       NVL (N_PROV_AMOUNT, 0) BONUS_PROV,
       NVL (GROSS_PAID, 0) GROSS_PAID,
         NVL (N_AMOUNT_PAYABLE, 0)
       + NVL (N_PROV_AMOUNT, 0)
       - NVL (GROSS_PAID, 0)
          CLAIM_OS,
       D_EVENT_DATE,
       D_CLAIM_DATE,
       A.V_LASTUPD_USER,
       V_PAYEE_NAME,
       V_VOU_NO,
       D_VOU_DATE,
       N_VOU_AMOUNT,
       V_CHQ_NO,
       V_CONTACT_NUMBER
  FROM CLMT_CLAIM_MASTER A,
       CLLU_TYPE_MASTER B,
       CLMM_STATUS_MASTER C,
       CLDT_CLAIM_EVENT_POLICY_LINK D,
       CLDT_PROVISION_MASTER E,
       CLDT_BONUS_PROVISION F,
       GNMT_POLICY_DETAIL G,
       GNMM_PLAN_MASTER M,
       GNDT_CUSTMOBILE_CONTACTS N,
       (SELECT DISTINCT V_CLAIM_NO, D_EVENT_DATE FROM CLDT_CLAIM_EVENT_LINK)
       H,
       (SELECT V_SOURCE_REF_NO,
               V_VOU_NO,
               NULL V_MAIN_VOU_NO,
               V_VOU_SOURCE,
               D_VOU_DATE,
               N_VOU_AMOUNT,
               V_CHQ_NO,
               V_PAYEE_NAME
          FROM PYMT_VOUCHER_ROOT A, PYMT_VOU_MASTER B
         WHERE A.V_MAIN_VOU_NO = B.V_MAIN_VOU_NO AND V_VOU_SOURCE = 'CLAIMS')
       I,
       (  SELECT V_CLAIM_NO, SUM (N_CLAIMANT_AMOUNT) GROSS_PAID
            FROM CLDT_CLAIMANT_MASTER
        GROUP BY V_CLAIM_NO) J
 WHERE     D.V_CLAIM_TYPE = B.V_CLAIM_TYPE(+)
       AND A.V_CLAIM_STATUS = C.V_STATUS_CODE
       AND A.V_CLAIM_NO = D.V_CLAIM_NO
       AND D.V_CLAIM_NO = E.V_CLAIM_NO(+)
       AND D.N_SUB_CLAIM_NO = E.N_SUB_CLAIM_NO(+)
       AND D.V_CLAIM_NO = F.V_CLAIM_NO(+)
       AND D.N_SUB_CLAIM_NO = F.N_SUB_CLAIM_NO(+)
       AND D.V_POLICY_NO = G.V_POLICY_NO
       AND D.N_SEQ_NO = G.N_SEQ_NO
       AND A.V_CLAIM_NO = H.V_CLAIM_NO
       AND A.V_CLAIM_NO = I.V_SOURCE_REF_NO(+)
       AND A.V_CLAIM_NO = J.V_CLAIM_NO(+)
       AND G.V_PLAN_CODE = M.V_PLAN_CODE
       AND G.V_PLAN_CODE = D.V_PLRI_CODE
       AND G.N_CUST_REF_NO = N.N_CUST_REF_NO(+)
       AND N.V_CONTACT_NUMBER(+) LIKE '0%'
--       AND TRUNC (D_CLAIM_DATE) BETWEEN NVL ( :P_FM_DT, TRUNC (D_CLAIM_DATE))
--                                    AND NVL ( :P_TO_DT, TRUNC (D_CLAIM_DATE))
       AND D.V_POLICY_NO NOT LIKE 'GL%'
       AND TO_CHAR(D_CLAIM_DATE, 'MON-YY') ='JAN-24'
       --AND EXTRACT(YEAR FROM D_CLAIM_DATE) = 2023
       )