



SELECT SUM(PREMIUM_AMOUNT)
FROM
(
SELECT CUST.V_NAME PYR_NAME,PROD.V_PLAN_DESC POLICY_TYPE, 
RCT.V_POLICY_NO POLICY_NO,  SUM(N_RECEIPT_AMT) PREMIUM_AMOUNT,
COUNT(V_RECEIPT_NO) PREMIUM_COUNT
FROM REMT_RECEIPT RCT,GNMT_CUSTOMER_MASTER  CUST,GNMT_POLICY POL, GNMM_PLAN_MASTER PROD
WHERE  RCT.V_RECEIPT_TABLE = 'DETAIL'
AND RCT.N_CUST_REF_NO = CUST.N_CUST_REF_NO(+)
AND RCT.V_POLICY_NO = POL.V_POLICY_NO(+)
 AND POL.V_PLAN_CODE = PROD.V_PLAN_CODE
AND RCT.V_POLICY_NO NOT LIKE 'GL%'
--AND EXTRACT(YEAR FROM D_RECEIPT_DATE) >= 2023
AND TRUNC(D_RECEIPT_DATE) BETWEEN :P_FROM_DT AND :P_TO_DT
GROUP BY CUST.V_NAME ,PROD.V_PLAN_DESC , RCT.V_POLICY_NO 
ORDER BY 4 DESC
)