bpg_Agency_benefits.BPC_COMM_TO_BENEFIT_POOL(P_END_DATE, P_LASTUPD_PROG,   P_LASTUPD_USER,  P_AGENT_NO,  P_DEDNS_FLAG, P_COMM_CHANNEL,   P_DATE);                    
 
bpg_Agency_benefits.BPC_BENEFIT_PAYMENT( P_END_DATE,  P_DEDN_FLAG ,    P_LASTUPD_PROG, P_LASTUPD_USER ,P_AGENT_NO ,   P_SEQ , P_CHANNEL_NO ,   P_DATE);