SELECT N_PROPOSER_REF_NO  FROM gnmt_policy where  V_POLICY_NO ='UI201800350905'

--N_PROPOSER_REF_NO

SELECT * FROM  gnmt_customer_master where N_PROPOSER_REF_NO = 250986
SELECT * FROM  gnmt_customer_master where  N_CUST_REF_NO = 230291
-- MUGABI KENNETH

select * from 

EDIT GNDT_CUSTOMER_IDENTIFICATION where N_CUST_REF_NO=230291;
 
insert into GNDT_CUSTOMER_IDENTIFICATION(N_CUST_REF_NO,V_IDEN_CODE,V_IDEN_NO,D_ISSUE,D_EXPIRY,V_STATUS,V_LASTUPD_USER,V_LASTUPD_PROG,V_LASTUPD_INFTIM)
VALUES(165020,'PIN','SID69016',NULL,NULL,'A','CSSESAAZI','TOAD','10-OCTOBER-2023');

select * from 
EDIT gnmt_customer_master where v_name like 'MUGABI%Kenn%'



-- commit 

250986

desc gnmt_customer_master


GNMT_POLICY    N_PROPOSER_REF_NO    FK_GNMT_POL_PROPREF_GNMT_CUS    GNMT_CUSTOMER_MASTER    PK_GNMT_CUSTOMER_MASTER    P    N_CUST_REF_NO


desc gnmt_policy