/* Formatted on 23/01/2020 12:21:32 (QP5 v5.256.13226.35538) */
select count (V_POLICY_NO)
FROM 
(
SELECT A.V_POLICY_NO,
       (B.V_NAME) ASSURED_NAME,
       F.V_ADD_ONE,
       F.V_ADD_TWO,
       TO_CHAR (A.D_DISPATCH_DATE, 'dd-MON-YYYY') DISPATCH_DATE,
       (D.V_AGENT_CODE) AGENT_CODE,
       (E.V_NAME) AGENT_NAME,
       (J.V_AGENT_CODE) AGENCY_MGR_CODE,
       (K.V_NAME) AGENCY_MGR_NAME,
       A.D_COMMENCEMENT,
       A.V_LASTUPD_USER,
       TO_CHAR (X.D_BRANCH_RECEIVED, 'dd-MON-YYYY') D_BRANCH_RECEIVED,
       X.V_SCANNED_BY,
       X.V_DISPATCH_STATUS
  FROM GNMT_POLICY A,
       GNMT_POLICY_DETAIL B,
       AMMT_POL_AG_COMM C,
       AMMM_AGENT_MASTER D,
       GNMT_CUSTOMER_MASTER E,
       GNDT_CUSTOMER_ADDRESS F,
       AMMT_POL_AG_COMM I,
       AMMM_AGENT_MASTER J,
       GNMT_CUSTOMER_MASTER K,
       PSDT_DISPATCH_HISTORY X
 WHERE     A.V_POLICY_NO = B.V_POLICY_NO
       AND A.V_POLICY_NO = X.V_POLICY_NO
       AND A.V_POLICY_NO = C.V_POLICY_NO(+)
       AND C.V_ROLE_CODE = 'SELLING'
       AND C.V_SOLD_BY = 'Y'
       AND C.V_STATUS = 'A'
       AND C.N_AGENT_NO = D.N_AGENT_NO
       --AND D.N_CHANNEL_NO = 10
       AND D.N_CUST_REF_NO = E.N_CUST_REF_NO
       AND B.N_CUST_REF_NO = F.N_CUST_REF_NO
       AND A.V_POLICY_NO = I.V_POLICY_NO
       AND I.V_RANK_CODE = 'SA'
       AND I.V_STATUS = 'A'
       AND I.N_AGENT_NO = J.N_AGENT_NO
       AND J.N_CUST_REF_NO = K.N_CUST_REF_NO
       AND X.V_DISPATCH_STATUS <> 'P'
       AND B.N_SEQ_NO = 1
       AND X.N_SL_NO =
              (SELECT MAX (N_SL_NO)
                 FROM PSDT_DISPATCH_HISTORY Z
                WHERE     X.V_POLICY_NO = Z.V_POLICY_NO
                      AND Z.V_DISPATCH_STATUS <> 'P')
       AND F.N_ADD_SEQ_NO IN (SELECT MAX (B.N_ADD_SEQ_NO)
                                FROM GNDT_CUSTOMER_ADDRESS B, GNMT_POLICY D
                               WHERE     D.N_PAYER_REF_NO = B.N_CUST_REF_NO
                                     AND D.V_POLICY_NO = A.V_POLICY_NO
                                     AND V_CORRES_ADDRESS = 'Y')
 --       AND EXTRACT(YEAR FROM A.D_DISPATCH_DATE) >=2023                            
      AND X.D_DT_DISPATCH BETWEEN ( :P_FM_DT) AND ( :P_TO_DT)
--AND a.D_COMMENCEMENT BETWEEN TO_DATE(NVL(?,TO_CHAR(TRUNC(SysDate,'YEAR'),'DD/MM/YYYY')),'DD/MM/YYYY') AND TO_DATE(NVL(?,TO_CHAR(TRUNC(SYSDATE),'DD/MM/YYYY')),'DD/MM/YYYY')
)