
--Ex

SELECT DISTINCT V_PLRI_CODE PRODUCT_CODE,
(SELECT V_PLAN_DESC FROM gnmm_plan_master WHERE V_PLAN_CODE=V_PLRI_CODE) PROD_NAME,
V_CHANNEL_NO,
(SELECT V_DESCRIPTION FROM AMMM_CHANNEL_MASTER  WHERE  N_CHANNEL_NO = V_CHANNEL_NO)
D_START,
N_PERCENT COMMISION_PERCENT,
V_RANK_CODE
FROM AMMM_PLAN_CHANNEL_COMM_LINK
WHERE V_CHANNEL_NO <> '10'
AND D_START BETWEEN '01-JAN-2023' AND SYSDATE


select * from gnmm_plan_channel_link 

SELECT * FROM AMMM_PLAN_CHANNEL_COMM_LINK where V_PLRI_CODE ='RGDII601'  --V_PLRI_CODE

SELECT * FROM AMMM_CHANNEL_MASTER 
select * from gnmm_plan_master  BGTL001

V_PLAN_CODE, V_PLAN_NAME, V_PLAN_DESC

