SELECT V_CLAIM_NO,V_PROFESSION_CODE, NVL (CAGN.V_NAME, CO.V_COMPANY_NAME) PAYEE, PR.N_CUST_REF_NO,PR.V_COMPANY_CODE,V_BRANCH_CODE, PR.V_LASTUPD_USER,N_AMOUNT_PAYABLE,N_PAID_AMNT,V_YOUR_REF_NO,D_LASTUPD_INFTIM,PR.V_REMARKS
FROM CLDT_CLAIM_PROF_FEE_LINK PR, GNMT_CUSTOMER_MASTER CAGN, GNMM_COMPANY_MASTER CO
WHERE  PR.N_CUST_REF_NO = CAGN.N_CUST_REF_NO(+)
AND PR.V_COMPANY_CODE = CO.V_COMPANY_CODE(+)
AND PR.V_BRANCH_CODE = CO.V_COMPANY_BRANCH(+)
--and ((TRUNC(PR.D_LASTUPD_INFTIM) BETWEEN :P_FROM_DT AND :P_TO_DT) OR(:P_FROM_DT IS NULL))