SELECT ROW_NUMBER () OVER (ORDER BY A.N_RECEIPT_SESSION) AS SERIAL_NUMBER,
         A.V_POLICY_NO V_POLICY_NO,
         V_NAME CLIENT_NAME,
         A.V_CURRENCY_CODE V_CURRENCY_CODE,
         A.N_RECEIPT_SESSION N_RECEIPT_SESSION,
         V_OTHER_REF_NO,
         D_OTHER_REF_DATE,
         V_RECEIPT_NO,
         INITCAP (B.V_RECEIPT_DESC) RECEIPT_TYPE,
         D_RECEIPT_DATE,
         TO_CHAR (N_RECEIPT_AMT, 'fm999,999,999.00') N_RECEIPT_AMT,
         DECODE (V_RECEIPT_STATUS,
                 'RE001', 'Processed',
                 'RE002', 'Cancelled')
            V_RECEIPT_STATUS,
         V_USER_CODE,
         NVL (V_INS_NUMBER, ' - ') INST_NUMBER,
         INS.V_DESC PAYMENT_MODE,
         BANKS.V_COMPANY_NAME || ' - ' || BANKS.V_COMPANY_BRANCH CLIENT_BANK,
            JHL_GEN_PKG.GET_DR_BANK (INS.V_INS_CODE,
                                     A.V_BRANCH_CODE,
                                     A.V_BUSINESS_CODE)
         || ' - '
         || JHL_GEN_PKG.GET_DR_BANK_CODE (INS.V_INS_CODE,
                                          A.V_BRANCH_CODE,
                                          A.V_BUSINESS_CODE)
            DR_BANK,
            V_STATUS_DESC POLICY_STATUS,
                         
             NVL(( SELECT DISTINCT ST.V_STATUS_DESC
FROM GN_CONTRACT_STATUS_LOG ST_LOG,GNMM_POLICY_STATUS_MASTER ST
WHERE ST_LOG.V_POLICY_NO  = X.V_POLICY_NO
 AND ST_LOG.V_CURR_STAT_CODE = ST.V_STATUS_CODE
AND  TO_DATE(ST_LOG.D_FROM,'DD/MM/RRRR')  <= TO_DATE(A.D_RECEIPT_DATE,'DD/MM/RRRR') 
AND TO_DATE(ST_LOG.D_TO,'DD/MM/RRRR')  >=TO_DATE(A.D_RECEIPT_DATE,'DD/MM/RRRR') 
AND ST_LOG.N_SEQ =  (SELECT MAX ( N_SEQ) FROM  GN_CONTRACT_STATUS_LOG LG WHERE LG.V_POLICY_NO  = X.V_POLICY_NO AND  TO_DATE(LG.D_FROM,'DD/MM/RRRR')  <= TO_DATE(A.D_RECEIPT_DATE,'DD/MM/RRRR') 
AND TO_DATE(LG.D_TO,'DD/MM/RRRR')  >=TO_DATE(A.D_RECEIPT_DATE,'DD/MM/RRRR')  )
),V_STATUS_DESC) STATUS_AT_ISSUE
    FROM REMT_RECEIPT A,
         REMM_RECEIPT_CODE B,
         GNMT_CUSTOMER_MASTER C,
         REMT_RECEIPT_INSTRUMENTS RCT_INS,
         REMM_INSTRUMENT INS,
         GNMM_COMPANY_MASTER BANKS,
         GNMT_POLICY X,
         GNMM_POLICY_STATUS_MASTER  STATUS
         
   WHERE   A.N_RECEIPT_SESSION = RCT_INS.N_RECEIPT_SESSION
         AND RCT_INS.V_INS_CODE = INS.V_INS_CODE
         AND A.V_RECEIPT_CODE = B.V_RECEIPT_CODE
         AND A.V_BUSINESS_CODE = B.V_BUSINESS_CODE
         AND A.N_CUST_REF_NO = C.N_CUST_REF_NO
         AND RCT_INS.V_INS_BANK = BANKS.V_COMPANY_CODE(+)
         AND RCT_INS.V_INS_BANK_BRANCH = BANKS.V_COMPANY_BRANCH(+)
         AND   A.V_POLICY_NO = X.V_POLICY_NO
           AND X.V_CNTR_STAT_CODE = STATUS.V_STATUS_CODE(+)
          AND A.V_BUSINESS_CODE = 'IND'
         AND V_BRANCH_CODE <> 'HO'
         AND V_RECEIPT_TABLE = 'DETAIL'
         AND V_PLAN_CODE NOT IN ('BSANN01', 'BANY001', 'BCEDANPT')
         AND TRUNC(D_RECEIPT_DATE)  BETWEEN  :P_FM_DT AND :P_TO_DT
        -- AND EXTRACT(YEAR FROM D_RECEIPT_DATE) >= 2023
          ORDER BY N_RECEIPT_SESSION