/* Formatted on 26/09/2018 6:39:59 PM (QP5 v5.256.13226.35538) */
  SELECT U.V_COMPANY_NAME,
         S.V_COMPANY_BRANCH,
         S.V_COMPANY_CODE,
         Q.V_OTHER_REF_NO,
         Q.V_RECEIPT_NO ISF_RECEIPT_NO,
         A.V_POLICY_NO,
         F.V_NAME POLICY_OWNER,
         Q.V_RECEIPT_CODE,
         Q.N_RECEIPT_AMT,
         Q.D_RECEIPT_DATE ALLOCATION_DATE,
         Q.D_OTHER_REF_DATE CASH_OFFICE_RECEIPT_DATE,
         Q.V_PREM_USAGE,
         S.V_EMP_ACCT_NO AS EMPLOYEE_NO,
         N_PAYER_REF_NO AS CUST_REF_NO,
         (SELECT V_IDEN_NO
            FROM GNDT_CUSTOMER_IDENTIFICATION K
           WHERE     V_IDEN_CODE = 'NIC'
                 AND N_CUST_REF_NO = A.N_PAYER_REF_NO
                 AND ROWNUM = 1)
            NATIONAL_ID,
         V_PMT_METHOD_NAME,
         N_IND_BASIC_PREM BASIC_PREMIUM,
         V_STATUS_DESC V_CURR_STATUS
    FROM GNMT_POLICY A,
         GNMT_POLICY_DETAIL B,
         AMMT_POL_AG_COMM C,
         GNLU_PAY_METHOD D,
         GNLU_FREQUENCY_MASTER E,
         GNMT_CUSTOMER_MASTER F,
         GNMM_POLICY_STATUS_MASTER G,
         GNMM_PLAN_MASTER H,
         PPDT_POLICY_DEDUCTION_DETAILS S,
         GNMM_COMPANY_MASTER U,
         REMT_RECEIPT Q
   WHERE     A.V_POLICY_NO = B.V_POLICY_NO
         AND A.V_POLICY_NO = C.V_POLICY_NO
         AND Q.V_POLICY_NO = A.V_POLICY_NO
         AND Q.V_RECEIPT_TABLE = 'DETAIL'
         AND A.V_PMT_METHOD_CODE = D.V_PMT_METHOD_CODE
         AND A.V_PYMT_FREQ = E.V_PYMT_FREQ
         AND S.V_COMPANY_CODE = U.V_COMPANY_CODE
         AND S.V_COMPANY_BRANCH = U.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = S.V_POLICY_NO
         AND V_ROLE_CODE = 'SELLING'
         AND C.V_STATUS = 'A'
         AND A.V_POLICY_NO NOT LIKE 'GL%'
         AND A.N_PAYER_REF_NO = F.N_CUST_REF_NO
         AND A.V_CNTR_STAT_CODE = G.V_STATUS_CODE
         AND A.V_PLAN_CODE = H.V_PLAN_CODE
      AND TRUNC (Q.D_RECEIPT_DATE) BETWEEN NVL(:P_FM_DT,TRUNC (Q.D_RECEIPT_DATE)) AND NVL(:P_TO_DT,TRUNC (Q.D_RECEIPT_DATE))
         --AND EXTRACT(YEAR FROM Q.D_RECEIPT_DATE)>= 2023
ORDER BY V_OTHER_REF_NO ASC