SELECT A.V_CLAIM_NO,
       C.V_POLICY_NO,
       D.V_COMPANY_NAME,
       V_CLIENT_NAME,
       H.V_PLAN_DESC,
       F.V_EVENT_DESC,
       D_EVENT_DATE,
       A.D_CLAIM_DATE,
      A.D_INTIMATION,
       CASE WHEN C.V_POLICY_NO = 'GL202202147755' THEN (0.55*B.N_AMOUNT_PAYB)
        WHEN (c.v_policy_no = 'GL201901727090' and  v_event_desc = 'ACCIDENTAL DEATH') THEN
            0
       WHEN c.v_policy_no = 'GL201901727090' and  v_event_desc != 'ACCIDENTAL DEATH' THEN
                0.5 * b.n_amount_payb
       ELSE B.N_AMOUNT_PAYB END AS JICK_LIABILITY,
       B.N_AMOUNT_PAYB,
       E.V_STATUS_DESC,
          ( SELECT RS.V_REASON_DESC
        FROM CLMM_STATUS_REASON_MASTER RS
        WHERE RS.V_REASON_CODE =I.V_STATUS_REASON) REASON,
        I.V_LASTUPD_INFTIM STATUS_DATE
  FROM CLMT_CLAIM_MASTER A,
       CLDT_CLAIM_EVENT_POLICY_LINK B,
       GNMT_POLICY C,
       GNMM_COMPANY_MASTER D,
       CLMM_STATUS_MASTER E,
       GNMM_EVENT_MASTER F,
       CLDT_CLAIM_POLICY_SETTLEMENT G,
       GNMM_PLAN_MASTER H,
       CLDT_CLAIM_EVENT_STATUS_LINK I,
       CLDT_CLAIM_EVENT_LINK J
 WHERE     A.V_CLAIM_NO = B.V_CLAIM_NO
       AND B.V_POLICY_NO = C.V_POLICY_NO
       AND C.V_COMPANY_CODE = D.V_COMPANY_CODE
       AND C.V_COMPANY_BRANCH = D.V_COMPANY_BRANCH
       AND C.V_GRP_IND_FLAG = 'G'
       AND B.V_EVENT_CODE = F.V_EVENT_CODE
       AND B.V_CLAIM_NO = G.V_CLAIM_NO(+)
       AND B.N_SEQ_NO = G.N_SEQ_NO(+)
       AND B.V_PLRI_CODE = H.V_PLAN_CODE
       AND B.N_AMOUNT_PAYB > 0
       AND B.V_CLAIM_NO = I.V_CLAIM_NO
       AND B.N_SUB_CLAIM_NO = I.N_SUB_CLAIM_NO
       AND B.V_CLAIM_NO = J.V_CLAIM_NO
       AND B.V_EVENT_CODE = J.V_EVENT_CODE
       AND I.V_STATUS_CODE = E.V_STATUS_CODE
       AND EXTRACT(YEAR FROM A.D_INTIMATION) >= 2023
--       AND TRUNC (A.D_INTIMATION) BETWEEN NVL ( :P_FM_DT,TRUNC (A.D_INTIMATION))  AND NVL ( :P_TO_DT,TRUNC (A.D_INTIMATION))
--       AND D.V_COMPANY_CODE = NVL(:P_COMPANY_CODE,D.V_COMPANY_CODE)
--        AND F.V_EVENT_CODE = NVL(:P_EVENT_CODE,F.V_EVENT_CODE)