
/* Formatted on 24/12/2019 10:50:48 (QP5 v5.256.13226.35538) */
-- sCHEME lISTING
SELECT * FROM 
(
SELECT TRIM (B.V_COMPANY_NAME) V_COMPANY_NAME,
       a.V_POLICY_NO,
       E.V_COMPANY_NAME V_AGENT_NAME,
       d.V_AGENT_CODE,
       (f.N_CONTRIBUTION) PREMIUM_LAST_RENEWAL,
       (f.N_SUM_COVERED) SUM_ASSURED,
       a.d_policy_end_date + 1 RENEWAL_DATE,
       a.V_LASTUPD_USER
  FROM GNMT_POLICY a,
       GNMM_COMPANY_MASTER b,
       AMMT_POL_AG_COMM c,
       AMMM_AGENT_MASTER d,
       GNMM_COMPANY_MASTER e,
       GNMT_QUOTATION f
 WHERE     A.V_COMPANY_CODE = B.V_COMPANY_CODE
       AND A.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
       AND A.V_POLICY_NO = C.V_POLICY_NO
       AND c.V_ROLE_CODE = 'SELLING'
       AND C.N_AGENT_NO = D.N_AGENT_NO
       AND D.V_COMPANY_CODE = E.V_COMPANY_CODE
       AND D.V_COMPANY_BRANCH = E.V_COMPANY_BRANCH
       AND A.V_QUOTATION_ID = F.V_QUOTATION_ID
       AND a.V_CNTR_STAT_CODE = 'NB010'
       AND c.V_STATUS = 'A'
      -- AND EXTRACT(YEAR FROM a.d_policy_end_date) >= 2023
       )
       WHERE TO_CHAR(RENEWAL_DATE, 'MON-YY') = 'JAN-24' 