

--SELECT * FROM GNMM_POLICY_STATUS_MASTER
SELECT * FROM 
(
SELECT 
N_CUST_REF_NO,
V_NAME,
V_POLICY_NO,
N_CONTRIBUTION,
N_TERM,
D_CNTR_START_DATE,
D_CNTR_END_DATE,
N_IND_SA,
V_CNTR_STAT_CODE,
(SELECT V_STATUS_DESC FROM GNMM_POLICY_STATUS_MASTER WHERE V_STATUS_CODE = V_CNTR_STAT_CODE) STATUS
FROM 
(
SELECT 
 A.N_CUST_REF_NO,
A.V_NAME,
B.V_POLICY_NO, 
B.N_CONTRIBUTION,
B.N_TERM,
B.D_CNTR_START_DATE,
B.D_CNTR_END_DATE,
B.N_IND_SA,
B.V_CNTR_STAT_CODE

FROM gnmt_customer_master A, GNMT_POLICY_DETAIL B
 WHERE A.N_CUST_REF_NO= B.N_CUST_REF_NO
 AND  B.V_POLICY_NO IN 
('UG202100793355',
'UG202200819295',
'UG202100703884',
'UG202200912476',
'UG202200825923'
) 
ORDER BY 6 DESC
)
) WHERE TRUNC(D_CNTR_START_DATE) BETWEEN '01-OCT-2023' AND '31-MAR-2024'

--WHERE ROWNUM <=10
